### ISSUE TITLE
dm3 translation in python 3 results in an Assertion Error

### ISSUE THREAD

**Issue by ssomnath** [pycroscopy/pycroscopy#104]
/io/translators/df_utils/parse_dm3.py in parse_dm_tag_data(f, outdata)
    227     else:
    228         _delim, header_len, data_type = get_from_file(f, "> 4s l l")
--> 229         assert(_delim == "%%%%")
    230         ret, header = dm_types[data_type](f)
    231         assert(header + 1 == header_len)

**Comment by CompPhysChris** [comment]
Should be fixed
https://github.com/pycroscopy/pycroscopy/commit/5c6aae6e04e51606c6faf3f3e7f973933e57ca8c
