### ISSUE TITLE
svd_utils.rebuild_svd bug in create_indexed_group

### ISSUE THREAD

**Issue by rajgiriUW** [pycroscopy/pycroscopy#156]
I think this was a bug in commit f327da7d98907b9ba09473055320e12ddb04e122 in updating svd_utils: 

line 328:
   rebuilt_grp = create_indexed_group('Rebuilt_Data', h5_svd_group.name[1:])

throws an error since create_indexed_group requires a h5Py group, not string.

I think this change should work (will test):
   rebuilt_grp = create_indexed_group(h5_svd_group, 'Rebuilt_Data')

**Comment by CompPhysChris** [comment]
Thanks for catching this Raj.  I'm implementing the fix now.
