### ISSUE TITLE
utf-8 problem with NanonisFile

### ISSUE THREAD

**Issue by donpatrice** [pycroscopy/pycroscopy#163]
I have a sxm file, that causes some problems when reading it with NanonisFile:
```
UnicodeDecodeError: 'utf-8' codec can't decode byte 0xb0 in position 67: invalid start byte
```
I found that the relevant part differs from [nanonispy](https://github.com/underchemist/nanonispy/blob/master/nanonispy/read.py) by
```
try:
    entry = line.strip().decode()
except UnicodeDecodeError:
    warnings.warn('{} has non-uft-8 characters, replacing them.'.format(f.name))
    entry = line.strip().decode('utf-8', errors='replace')
```
In particular these lines are missing in pycroscopy. Is there a reason for this? Adding these lines solves my problem.

**Comment by CompPhysChris** [comment]
Pycroscopy is currently using it's own version of nanonispy.  When we first added it, the package hadn't been updated in years.  Now that it's been updated, we will likely add it to the requirements list and remove our copy of the code.

**Comment by CompPhysChris** [comment]
Updating nanonispy files seems to have fixed this.  Closing issue
