### ISSUE TITLE
latest pycroscopy build (0.0a6) has the following error during import

### ISSUE THREAD

**Issue by nlaanait** [pycroscopy/pycroscopy#18]
/Users/nl7/anaconda2/lib/python2.7/site-packages/pycroscopy/io/hdf_utils.py in <module>()
     10 from warnings import warn
     11 import numpy as np
---> 12 from .microdata import MicroDataset
     13 
     14 **all** = ['getDataSet', 'getH5DsetRefs', 'getH5RegRefIndices', 'get_dimensionality', 'get_sort_order',

ImportError: No module named microdata

┆Issue is synchronized with this [Asana task](https://app.asana.com/0/200029249765524/200212102670085)

**Comment by CompPhysChris** [comment]
I just confirmed that pip install pycroscopy + import pycroscopy works fine on my Linux laptop,  The install works with no errors on my Windows desktop, but I get the error when I try to import.
