### ISSUE TITLE
PIFM and HyperImage Translators

### ISSUE THREAD

**Issue by ssomnath** [pycroscopy/pycroscopy#199]
The base code that makes up the translator already exists [here](https://github.com/rajgiriUW/pifm_translator). Need to finish converting this to a formal Pycroscopy translator

**Comment by rajgiriUW** [comment]
I believe this is resolved in #201 / #202

**Comment by ssomnath** [comment]
@rajgiriUW and @kongjy - I am not an expert here but does HyperImage data already have a translator? I remember these being separate entities when we first discussed translation. Is this part of the PiFMTranslator?

**Comment by kongjy** [comment]
Yes, they were separate but we have combined them
