### ISSUE TITLE
Processing functions failing to find existing results

### ISSUE THREAD

**Issue by ramav87** [pycroscopy/pycroscopy#203]
Calling SVD or NMF (or any decomposition method) twice with same parameters does not result in return of results on second pass. Note given is

Note: Decomposition has already been performed PARTIALLY with the same parameters. compute() will resuming computation in the last group below. 

despite no changes to input parameters and completion of the decomposition. This needs to be remedied.

**Comment by ssomnath** [comment]
Fixed with [this](https://github.com/pycroscopy/pyUSID/commit/0ce2778f0d36a5aeaf9c5d126bf3832ac184dc37)
