### ISSUE TITLE
Error during Importing pycroscopy

### ISSUE THREAD

**Issue by ayfliu** [pycroscopy/pycroscopy#205]
I have this error when importing pycroscopy (0.60.3)

~\PyMOL\envs\PyEMMA\lib\site-packages\pycroscopy\io\hdf_writer.py in <module>
     14 import h5py
     15 
---> 16 from pyUSID.io.hdf_utils import assign_group_index, write_simple_attrs, attempt_reg_ref_build, write_region_references
     17 from .virtual_data import VirtualGroup, VirtualDataset, VirtualData
     18 from ..__version__ import version

ImportError: cannot import name 'attempt_reg_ref_build'

I tried to look up attempt_reg_ref_build but I cannot find it in pyUSID documentation

I have pyUSID 0.0.6.1 imported in python 3.6.7

**Comment by ramav87** [comment]
Yes, this is a known issue that has been fixed on the master. Please clone master until the pypi version is updated.

**Comment by ssomnath** [comment]
You should be able to use pyUSID 0.0.6.2 alternatively.

**Comment by ayfliu** [comment]
That was solved by cloning the master. Thanks!
