### ISSUE TITLE
Generic data visualizer

### ISSUE THREAD

**Issue by ssomnath** [pycroscopy/pycroscopy#22]
Should take any MAIN dataset regardless of the dimensionality. Core components implemented in viz.jupyter_utils

┆Issue is synchronized with this [Asana task](https://app.asana.com/0/200029249765524/202079868929510)

**Comment by CompPhysChris** [comment]
A very simplistic version has been implemented and will be improved at a later time.

**Comment by ramav87** [comment]
Implemented in USID
