### ISSUE TITLE
BE_Jupyter Notebook call to uiGetFile

### ISSUE THREAD

**Issue by jagar2** [pycroscopy/pycroscopy#96]
---------------------------------------------------------------------------
AttributeError                            Traceback (most recent call last)
<ipython-input-6-5e0593bca935> in <module>()
----> 1 input_file_path = px.io.io_utils.uiGetFile(caption='Select translated .h5 file or raw experiment data',
      2                                         filter='Parameters for raw BE data (*.txt *.mat *xls *.xlsx);; \
      3                                         Translated file (*.h5)')
      4 
      5 (data_dir, data_name) = os.path.split(input_file_path)

AttributeError: module 'pycroscopy.io.io_utils' has no attribute 'uiGetFile'

The io_utils is missing the uiGetFile

**Comment by ssomnath** [comment]
Fixed in the latest build
